# Generated by Django 4.1.1 on 2022-11-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likers',
            new_name='liker',
        ),
    ]
