# Generated by Django 4.1.1 on 2022-11-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_likers_post_liker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liker',
            new_name='likers',
        ),
    ]
